### PR TITLE
 Added preference to hide low priority notifications

### PR DESCRIPTION
**Pull request by ns130291**
I added a preference to hide low priority notifications like weather updates by Google Now from appearing as heads up notification.

### CODE REVIEW

**Comment by GermainZ** [comment]
Could you please update this/send another PR? Otherwise I could apply the commit manually. Thanks :)

**Comment by ns130291** [comment]
I hope I merged it the right way

**Comment by GermainZ** [comment]
Ideally you'd just squash the commits you've made since they're all for the very same thing (and the two other commits are just noise: removing an unused import and a merge).

This should do it (assuming upstream = this repo, not yours):
`git pull --rebase upstream master`
This will basically remove your commits, pull the new changes then reapply your commits (you may need to fix merge errors using `git mergetool`).

Now squash your commits into one:
`git rebase -i origin/master`
Find commits 7f63a7d, 3cce943 and 2b8cc09 (should be the last three commits), then replace "pick" by "squash" for the second and third commits (leave the first as it is).

Finally, force push your changes:
`git push -f`

A tip for the future: when merging for a PR, always use `git pull --rebase upstream master` instead of `git pull`. It's cleaner and avoids redundant "merge" commits.

Thanks!

**Comment by ns130291** [comment]
I tried to rebase it, but I'm not happy with the result

**Comment by GermainZ** [comment]
Alright, I cherry-picked the commit. Thanks :)

**Pull request closed without merging**
