### PR TITLE
Add gravity option

### PR DESCRIPTION
**Pull request by 75py**
Added option "Notification gravity."
I think Gravity.BOTTOM is better than TOP.

### CODE REVIEW

**Comment by GermainZ** [comment]
Why is the custom class necessary? Just set an OnPreferenceChangeListener in SettingsActivity.

**Comment by 75py** [comment]
Because findPreference method is deprecated.
If you don't accept it, I'll remove it and re-pull request. Is that OK?

**Comment by MohammadAG** [comment]
findPreference is deprecated in PreferenceActivity, ideally, we'd switch to PreferenceFragment in a PreferenceActivity, but that's unnecessary overhead really.

**Comment by 75py** [comment]
I see. I'll fix soon.

**Pull request closed without merging**
