### PR TITLE
Don't show headsup if notification is clearable

### PR DESCRIPTION
**Pull request by theknut**
Don't show headsup if the notification is not clearable. This applies for the IME switcher, LUX, Wireless ADB, ... for example.

### CODE REVIEW

**Comment by theknut** [comment]
Blacklist added with 8db670d.
Close.

**Comment by theknut** [comment]
@MohammadAG can you please include an option to not show non clearable notification nonetheless? It doesn't make sense to show those imho.

**Comment by MohammadAG** [comment]
Oh, it's not part of GermainZ's patches, next version it is!

**Comment by GermainZ** [comment]
If you add this before I do, based on the comments on XDA, this should be an option.
On Mon, Jun 23, 2014 at 12:32 AM, Mohammad Abu-Garbeyyeh notifications@github.com wrote:Oh, it's not part of GermainZ's patches, next version it is!

**Comment by theknut** [comment]
Thanks Mohammad! I just want to give a heads up (oh my...) my patch only
kind of works. Yes, they'll not be shown but it also messes up the order of
the notifications. I use lux for example which posts a notification with
the highest priority and not clearable, so it's always the first. After
using my patch it happens that the priority is not kept. So notifications
like Google Now would be on the top instead of the lux one. Just letting
you know because it looks like it's doing the job at first glance but it's
not.

And yes I agree, make it optional.
Am 22.06.2014 23:34 schrieb "GermainZ" notifications@github.com:

**Comment by MohammadAG** [comment]
Done in 1.2, not sure if it messes up priorities, though I don't see why it should...

I'm using isOngoing rather than isClearable though.

**Comment by theknut** [comment]
There you go... http://forum.xda-developers.com/showpost.php?p=53605124&postcount=100
I'm surprised it got reported only once. Maybe we could block "setNotification" rather than blocking it from interrupting? I'll try that when I get home.

**Pull request closed without merging**
